"""端点映射 —— 由服务端注册表生成，勿手改。

重新生成：仓库根目录执行  cd api && python scripts/gen_sdk_endpoints.py
"""

ENDPOINTS = {
    "daily": {"path": "/v1/market/daily", "summary": "日线行情（OHLC）"},
    "fundamentals": {"path": "/v1/market/fundamentals", "summary": "每日指标（PE/PB/换手率/市值）"},
    "adj_factor": {"path": "/v1/market/adj-factor", "summary": "复权因子"},
    "technical_factors": {"path": "/v1/market/technical-factors", "summary": "技术面因子"},
    "technical_factors_pro": {"path": "/v1/market/technical-factors-pro", "summary": "技术面因子（专业版，含复权价+技术指标）"},
    "margin": {"path": "/v1/market/margin", "summary": "融资融券明细"},
    "block_trade": {"path": "/v1/market/block-trade", "summary": "大宗交易"},
    "top_list": {"path": "/v1/market/top-list", "summary": "龙虎榜（个股）"},
    "top_inst": {"path": "/v1/market/top-inst", "summary": "龙虎榜（机构席位）"},
    "shareholders": {"path": "/v1/market/shareholders", "summary": "股东户数"},
    "holder_trade": {"path": "/v1/market/holder-trade", "summary": "重要股东增减持"},
    "limit_list": {"path": "/v1/market/limit-list", "summary": "涨跌停榜单"},
    "concepts": {"path": "/v1/market/concepts", "summary": "概念/题材板块指数"},
    "concept_members": {"path": "/v1/market/concept-members", "summary": "概念/题材板块成分股"},
    "moneyflow": {"path": "/v1/flows/moneyflow", "summary": "个股资金流向"},
    "moneyflow_hsgt": {"path": "/v1/flows/moneyflow-hsgt", "summary": "沪深港通资金流向（全市场）"},
    "northbound_holdings": {"path": "/v1/flows/northbound-holdings", "summary": "北向持股明细"},
    "southbound_holdings": {"path": "/v1/flows/southbound-holdings", "summary": "南向（港股通）持股明细"},
    "distribution": {"path": "/v1/chips/distribution", "summary": "筹码分布与胜率"},
    "fx_daily": {"path": "/v1/fx/daily", "summary": "外汇日线（默认 USDCNH）"},
    "index_daily": {"path": "/v1/indices/daily", "summary": "指数日线（默认上证综指）"},
    "index_weight": {"path": "/v1/indices/index-weight", "summary": "指数成分与权重"},
    "indicators": {"path": "/v1/financials/indicators", "summary": "财务指标"},
    "income": {"path": "/v1/financials/income", "summary": "利润表"},
    "balance_sheet": {"path": "/v1/financials/balance-sheet", "summary": "资产负债表"},
    "cash_flow": {"path": "/v1/financials/cash-flow", "summary": "现金流量表"},
    "forecast": {"path": "/v1/financials/forecast", "summary": "业绩预告"},
    "express": {"path": "/v1/financials/express", "summary": "业绩快报"},
    "analyst_reports": {"path": "/v1/financials/analyst-reports", "summary": "券商研报盈利预测"},
    "audit": {"path": "/v1/financials/audit", "summary": "财务审计意见"},
    "main_business": {"path": "/v1/financials/main-business", "summary": "主营业务构成"},
    "disclosure_date": {"path": "/v1/financials/disclosure-date", "summary": "财报披露日历"},
    "dividend": {"path": "/v1/shareholders/dividend", "summary": "分红送股"},
    "stocks": {"path": "/v1/reference/stocks", "summary": "股票列表"},
    "industries": {"path": "/v1/reference/industries", "summary": "申万行业分类"},
    "trade_calendar": {"path": "/v1/reference/trade-calendar", "summary": "交易日历（默认上交所）"},
    "realtime": {"path": "/v1/market/realtime", "summary": "实时行情快照（最多 200 只）"},
    "news_flash": {"path": "/v1/news/flash", "summary": "财经快讯（财联社/金十/新浪）"},
}
