"""端点映射 —— 由服务端注册表生成，勿手改。

重新生成：仓库根目录执行  cd api && python scripts/gen_sdk_endpoints.py
"""

ENDPOINTS = {
    "daily": {"path": "/v1/market/daily", "summary": "日线行情（OHLC）", "tier": "free"},
    "fundamentals": {"path": "/v1/market/fundamentals", "summary": "每日指标（PE/PB/换手率/市值）", "tier": "starter"},
    "adj_factor": {"path": "/v1/market/adj-factor", "summary": "复权因子", "tier": "starter"},
    "technical_factors": {"path": "/v1/market/technical-factors", "summary": "技术面因子", "tier": "pro"},
    "technical_factors_pro": {"path": "/v1/market/technical-factors-pro", "summary": "技术面因子（专业版，含复权价+技术指标）", "tier": "expert"},
    "margin": {"path": "/v1/market/margin", "summary": "融资融券明细", "tier": "pro"},
    "block_trade": {"path": "/v1/market/block-trade", "summary": "大宗交易", "tier": "pro"},
    "top_list": {"path": "/v1/market/top-list", "summary": "龙虎榜（个股）", "tier": "pro"},
    "top_inst": {"path": "/v1/market/top-inst", "summary": "龙虎榜（机构席位）", "tier": "pro"},
    "shareholders": {"path": "/v1/market/shareholders", "summary": "股东户数", "tier": "pro"},
    "holder_trade": {"path": "/v1/market/holder-trade", "summary": "重要股东增减持", "tier": "pro"},
    "limit_list": {"path": "/v1/market/limit-list", "summary": "涨跌停榜单", "tier": "pro"},
    "concepts": {"path": "/v1/market/concepts", "summary": "概念/题材板块指数", "tier": "pro"},
    "concept_members": {"path": "/v1/market/concept-members", "summary": "概念/题材板块成分股", "tier": "pro"},
    "moneyflow": {"path": "/v1/flows/moneyflow", "summary": "个股资金流向", "tier": "pro"},
    "moneyflow_hsgt": {"path": "/v1/flows/moneyflow-hsgt", "summary": "沪深港通资金流向（全市场）", "tier": "pro"},
    "northbound_holdings": {"path": "/v1/flows/northbound-holdings", "summary": "北向持股明细", "tier": "pro"},
    "southbound_holdings": {"path": "/v1/flows/southbound-holdings", "summary": "南向（港股通）持股明细", "tier": "pro"},
    "distribution": {"path": "/v1/chips/distribution", "summary": "筹码分布与胜率", "tier": "expert"},
    "fx_daily": {"path": "/v1/fx/daily", "summary": "外汇日线（默认 USDCNH）", "tier": "free"},
    "index_daily": {"path": "/v1/indices/daily", "summary": "指数日线（默认上证综指）", "tier": "free"},
    "index_weight": {"path": "/v1/indices/index-weight", "summary": "指数成分与权重", "tier": "starter"},
    "basic": {"path": "/v1/etf/basic", "summary": "ETF 基础信息", "tier": "free"},
    "etf_daily": {"path": "/v1/etf/daily", "summary": "ETF 日线行情", "tier": "free"},
    "etf_adj_factor": {"path": "/v1/etf/adj-factor", "summary": "ETF 复权因子", "tier": "free"},
    "nav": {"path": "/v1/etf/nav", "summary": "ETF 净值", "tier": "starter"},
    "portfolio": {"path": "/v1/etf/portfolio", "summary": "ETF 持仓明细", "tier": "pro"},
    "share_size": {"path": "/v1/etf/share-size", "summary": "ETF 份额与规模", "tier": "starter"},
    "tracking_indices": {"path": "/v1/etf/tracking-indices", "summary": "ETF 跟踪指数基础信息", "tier": "starter"},
    "indicators": {"path": "/v1/financials/indicators", "summary": "财务指标", "tier": "starter"},
    "income": {"path": "/v1/financials/income", "summary": "利润表", "tier": "starter"},
    "balance_sheet": {"path": "/v1/financials/balance-sheet", "summary": "资产负债表", "tier": "starter"},
    "cash_flow": {"path": "/v1/financials/cash-flow", "summary": "现金流量表", "tier": "starter"},
    "forecast": {"path": "/v1/financials/forecast", "summary": "业绩预告", "tier": "starter"},
    "express": {"path": "/v1/financials/express", "summary": "业绩快报", "tier": "starter"},
    "analyst_reports": {"path": "/v1/financials/analyst-reports", "summary": "券商研报盈利预测", "tier": "pro"},
    "audit": {"path": "/v1/financials/audit", "summary": "财务审计意见", "tier": "pro"},
    "main_business": {"path": "/v1/financials/main-business", "summary": "主营业务构成", "tier": "pro"},
    "disclosure_date": {"path": "/v1/financials/disclosure-date", "summary": "财报披露日历", "tier": "pro"},
    "dividend": {"path": "/v1/shareholders/dividend", "summary": "分红送股", "tier": "starter"},
    "stocks": {"path": "/v1/reference/stocks", "summary": "股票列表", "tier": "free"},
    "industries": {"path": "/v1/reference/industries", "summary": "申万行业分类", "tier": "free"},
    "trade_calendar": {"path": "/v1/reference/trade-calendar", "summary": "交易日历（默认上交所）", "tier": "free"},
    "realtime": {"path": "/v1/market/realtime", "summary": "实时行情快照（最多 200 只）", "tier": "starter"},
    "news_flash": {"path": "/v1/news/flash", "summary": "财经快讯（财联社/金十/新浪）", "tier": "starter"},
}
